#!/usr/bin/env python3
"""Bridge NEW Robinhood watchlist → Finwiz registry + optional Elite sync.

Examples:
  py -3 scripts/enrich_robinhood_watchlist.py
  py -3 scripts/enrich_robinhood_watchlist.py --sync-elite --limit 40
  py -3 scripts/enrich_robinhood_watchlist.py --from "D:/Finwiz Screener Stocks Trading Assistant/Robinhood.com Trading Watchlist/NEW_Robinhood_com_Trading_Watchlist.json"
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from auto_add_tickers import upsert_candidate  # noqa: E402
from lib_finwiz import ROOT, WATCHLISTS_DIR, load_json, rebuild_index, save_json  # noqa: E402

DEFAULT_SRC = Path(
    r"D:\Finwiz Screener Stocks Trading Assistant\Robinhood.com Trading Watchlist\NEW_Robinhood_com_Trading_Watchlist.json"
)
RH_DIR = ROOT / "data" / "robinhood"
RH_POSITIONS = RH_DIR / "positions.json"
RH_CSV = RH_DIR / "positions.csv"
WL_PATH = WATCHLISTS_DIR / "robinhood-retail.json"


def load_positions(src: Path) -> list[dict]:
    data = json.loads(src.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise SystemExit(f"Expected JSON array in {src}")
    out = []
    for r in data:
        t = str(r.get("ticker") or "").strip().upper()
        if not t:
            continue
        out.append({**r, "ticker": t})
    return out


def write_watchlist(tickers: list[str]) -> None:
    wl = {
        "name": "robinhood-retail",
        "description": "NEW Robinhood.com Trading Watchlist mapped into Finwiz Screener",
        "updated": date.today().isoformat(),
        "source": "data/robinhood/positions.json",
        "tickers": tickers,
        "finviz_compare_url": "https://finviz.com/screener.ashx?v=111&t=" + ",".join(tickers[:60]),
        "notes": "Generated by scripts/enrich_robinhood_watchlist.py — research desk only; not order routing.",
    }
    save_json(WL_PATH, wl)


def sync_elite_chunked(tickers: list[str], chunk: int = 40) -> dict:
    from finviz_elite import elite_configured, sync_tickers

    if not elite_configured():
        return {"ok": False, "reason": "FINVIZ_API_KEY not configured"}

    patched = 0
    errors: list[str] = []
    updated: list[str] = []
    for i in range(0, len(tickers), chunk):
        batch = tickers[i : i + chunk]
        try:
            result = sync_tickers(batch)
            n = int(result.get("count") or 0)
            patched += n
            updated.extend(result.get("updated") or [])
            print(f"  Elite chunk {i // chunk + 1}: {len(batch)} tickers → patched {n}", flush=True)
            if not result.get("ok"):
                errors.append(str(result.get("reason") or result))
        except Exception as exc:
            errors.append(f"chunk@{i}: {exc}")
            print(f"  Elite chunk failed: {exc}", flush=True)
    return {"ok": not errors, "patched": patched, "updated": updated, "errors": errors}


def main() -> int:
    p = argparse.ArgumentParser(description="Enrich Robinhood watchlist into Finwiz")
    p.add_argument("--from", dest="src", default=str(DEFAULT_SRC), help="Source positions JSON")
    p.add_argument("--status", default="watch", help="Ticker status tag (default: watch)")
    p.add_argument("--sync-elite", action="store_true", help="Pull Finviz Elite metrics/technicals/recom")
    p.add_argument("--limit", type=int, default=0, help="Limit tickers (0 = all)")
    p.add_argument("--no-upsert", action="store_true", help="Only copy positions + watchlist JSON")
    p.add_argument("--no-rebuild", action="store_true", help="Skip search_index rebuild")
    args = p.parse_args()

    src = Path(args.src)
    if not src.exists():
        # Fall back to already-copied Finwiz copy
        if RH_POSITIONS.exists():
            src = RH_POSITIONS
        else:
            raise SystemExit(f"Source not found: {args.src}")

    RH_DIR.mkdir(parents=True, exist_ok=True)
    positions = load_positions(src)
    # Always persist the full source set; --limit only scopes upsert/Elite.
    RH_POSITIONS.write_text(json.dumps(positions, indent=2), encoding="utf-8")
    csv_src = src.with_suffix(".csv")
    if csv_src.exists():
        shutil.copy2(csv_src, RH_CSV)
    print(f"Wrote {RH_POSITIONS} ({len(positions)} rows)", flush=True)

    tickers = [r["ticker"] for r in positions]
    seen = set()
    uniq = []
    for t in tickers:
        if t not in seen:
            seen.add(t)
            uniq.append(t)
    write_watchlist(uniq)
    print(f"Wrote {WL_PATH} ({len(uniq)} tickers)", flush=True)

    work = uniq[: args.limit] if args.limit and args.limit > 0 else uniq

    if not args.no_upsert:
        for t in work:
            upsert_candidate(t, status=args.status)
        print(f"Upserted {len(work)} ticker JSON profiles (status={args.status})", flush=True)

    if args.sync_elite:
        print(f"Syncing Finviz Elite for {len(work)} tickers…", flush=True)
        result = sync_elite_chunked(work)
        print(result, flush=True)

    if not args.no_rebuild:
        idx = rebuild_index()
        print(f"Rebuilt index: {len(idx.get('docs') or [])} docs", flush=True)

    print("Done. Open dashboard → Robinhood Watchlist page.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
